stages:
  - checks
  - deploy-test

&python
  language: python
  install:
    - pip install poetry
    - poetry install -v

jobs:
  include:
  - <<: *python
    python: 3.6
    script:
    - make coverage
  - <<: *python
    script:
    - make style
